### ISSUE TITLE
Build C libraries with the Python build system

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#713]
Currently numerous C libraries (e.g. lz4, libxml) and also some packages (e.g. six, parso)  are packaged with Makefiles in the root folder of pyodide. I this can be confusing for new contributors and is not sustainable long term, as it makes it hard to distinguish what is pyodide code and what are packages.

Related to https://github.com/iodide-project/pyodide/issues/38

I think we should,
 - [x] move all of those libraires under `packages/` folder (while keeping the use of Makefiles). This would be just a path change. Done in https://github.com/iodide-project/pyodide/pull/714
 - [ ] migrate these libraries to be defined with a `meta.yaml` and build them with the Python build system. This would allow managing dependencies better (e.g. build LAPACK only when scipy is built etc).

**Comment by rth** [comment]
To give a more concrete example for step 1, consider [`packages/zlib/Makefile`](https://github.com/iodide-project/pyodide/blob/master/packages/zlib/Makefile), we would want to replace it with something along the lines of,

**packages/zlib/meta.yaml**
```yaml
package:
  name: zlib
  version: 1.2.11
source:
  sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
  url: https://zlib.net/zlib-1.2.11.tar.gz
build:
  script:
    - emconfigure ./configure  --prefix=$(SRC)
    - emmake make install -j ${PYODIDE_JOBS:-3} 
```

and then,
 1. adjust [pyodide_build/buildpkg.py](https://github.com/iodide-project/pyodide/blob/master/pyodide_build/buildpkg.py#L230) to these build script commands if they are available and fall back to the `python setup.py` command otherwise as it's done now.
 2. figure out how to pass environment variables such as `PYODIDE_JOBS` and also some paths variables (here `$SRC` which is the current dir). There is probably some standard approaches of doing this with conda `meta.yaml`. It would require reading the `meta.yaml` spec and maybe also browsing a few examples on conda-forge.
 3. Add `zlib` as a requirements to any package that needs it, here lxml.
 4. Remove the corresponding command form the [main Makefile](https://github.com/iodide-project/pyodide/blob/bc3ffaae427e35b9ecd9a6216fadad031a363a47/Makefile#L268).

**Note:** zlib is required by libxml, so it would likely need to be ported at the same time.  Or one could start with a different package, for instance lz4.
